name = "jiux-release-cron"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "你的D1数据库名称"
database_id = "你的D1数据库ID"

[triggers]
crons = ["0 0 * * *"]
